services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magicape
      POSTGRES_DB: chatroom
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: chatroom-api
    environment:
      DATABASE_URL: postgresql://postgres:magicape@db:5432/chatroom
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgres-data:
